---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: rag-sep4-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rag-sep4-2 
  name: rag-sep4-2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi